services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: moovitamix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: moovitamix_fastapi:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: moovitamix
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./logs:/app/logs

volumes:
  postgres_data: