# Use Python base image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the FastAPI Flux app
COPY ./src/moovitamixflux_fastapi /app

# Expose the port the service will run on
EXPOSE 8001

# Command to run the FastAPI service
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
